name: Deploy to Dev

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test-and-plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Chekout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run pytest
        run: python -m pytest tests/ -v

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Create Terraform.tfvars
        working-directory: ./alwaha-ias-terraform
        run: |
          cat> terraform.tfvars <<EOF
          project_name = "Al-Waha-Bank-Real-Time-Fraud"
          environment = ["dev"]
          location = "East US"
          subscription_id = "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          databricks_account_id = "${{ secrets.DATABRICKS_ACCOUNT_ID }}"
          azure_tenant_id = "${{ secrets.AZURE_TENANT_ID }}"
          tags = {
            project = "AlWaha-banking",
            Environment = "development",
            ManagedBy = "Terraform",
            Domain = "Fraud-AML"
          }
          EOF

      - name: Terraform init
        working-directory: ./alwaha-ias-terraform
        run: terraform init

      - name: Terraform plan
        working-directory: ./alwaha-ias-terraform
        run: terraform plan

  deploy-dev:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Create Terraform.tfvars
        working-directory: ./alwaha-ias-terraform
        run: |
          cat > terraform.tfvars <<EOF
          project_name = "alwaha"
          environment = ["dev"]
          location = "East US"
          subscription_id = "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          databricks_account_id = "${{ secrets.DATABRICKS_ACCOUNT_ID }}"
          azure_tenant_id = "${{ secrets.AZURE_TENANT_ID }}"
          databricks_token = "${{ secrets.DATABRICKS_TOKEN }}"
          azure_client_id = "${{ secrets.AZURE_APP_ID }}"
          azure_client_secret = "${{ secrets.AZURE_APP_PASSWORD }}"
          tags = {
            project = "ALWaha-Banking",
            Environment = "development",
            ManagedBy = "Terraform",
            Domain = "Fraud-AML"
          }
          EOF

      - name: Terraform Init
        working-directory: ./alwaha-ias-terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./alwaha-ias-terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./alwaha-ias-terraform
        run: terraform apply -auto-approve

      - name: Install Databricks CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Deploy Databricks Bundle to Dev
        run: databricks bundle deploy --target dev
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN}}